[package]
name = "reverse_string"
version = "1.0.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]

[features]
grapheme = []

[dependencies]
unicode-segmentation = "0.1.3"
